name: Update Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Your Mom
       #run: chmod +x README.sh && ./README.sh
        run: python3 README.py



