name: Update Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Your Mom
        run: chmod +x README.sh README.py && ./README.py
        #run: python3 README



